# Generated by Django 4.2.4 on 2023-09-30 01:54

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.SmallIntegerField(choices=[(0, '初级'), (1, '中级'), (2, '高级')], default=1, verbose_name='难度等级'),
        ),
        migrations.AlterField(
            model_name='course',
            name='attachment_path',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=1000, null=True, verbose_name='课件路径'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_viedo',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=255, null=True, verbose_name='封面视频'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='详情介绍'),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='remark',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='分类描述'),
        ),
        migrations.AlterField(
            model_name='coursechapter',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='章节介绍'),
        ),
        migrations.AlterField(
            model_name='coursedirection',
            name='remark',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='方向描述'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='brief',
            field=ckeditor.fields.RichTextField(max_length=1024, verbose_name='讲师描述'),
        ),
    ]
